apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: elq-webhook
  name: elq-webhook
  namespace: ${NAMESPACE}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'elq-webhook:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'python:3.5'
        namespace: openshift
    type: Source
  triggers: []
