apiVersion: v1
kind: Route
metadata:
  labels:
    app: elq-webhook
  name: elq-webhook
  namespace: ${NAMESPACE}
spec:
  host: elq-webhook-${NAMESPACE}.${OPENSHIFT_ROUTE_HOST}
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: elq-webhook
    weight: 100
  wildcardPolicy: None
