apiVersion: v1
kind: Service
metadata:
  labels:
    app: elq-webhook
  name: elq-webhook
  namespace: ${NAMESPACE}
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: elq-webhook
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
